### ISSUE TITLE
Zusammenlegen

### ISSUE THREAD

**Issue by DirkRusche** [jaads/Another-modular-HBRS-LaTeX-template-Vorlage#1]
Nachdem mein altes Ticket *verschwunden* ist, probiere ich es nochmal.

Ich arbeite derzeit auch nebenbei an einer LaTeX Vorlage. Hast du Lust die Projekte zusammen zu legen? 😄

**Comment by jaads** [comment]
Wow das Issue habe ich bis heute komplett übersehen. Jetzt für meine Master-Thesis habe ich das Projekt nochmal geöffnet und sehe es erst. Schade die Idee war gut, das hätte man machen können. Ich gehe davon aus, dass es jetzt zu spät ist x)

**Comment by DirkRusche** [comment]
Haha. Kein Problem, ja mittlerweile hat es sich erledigt.

Viel Erfolg bei Deiner Masterarbeit!
